# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb69b720b4ad3e455686169a89dbdfb0e3a2b19132eb8339c8a0668d34bc7ca4cc132481aa925abccdba7a4dc3b84b499921090c4ff3e828be851cedf302dc89

test:
  secret_key_base: 381bcce5852228eda39180b491b3ff6786bd6cb7d64ede376fccbc49665820f0e4cdcf50f8a105bb3d27145c0b9905fb08e5410d0486a082ee2878708c42a637

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
